spring.application.name=multidigital-wallet

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/payflow_db
spring.datasource.username=${POSTGRES_USER:payflowAdmin}
spring.datasource.password=${POSTGRES_PASSWORD:PayflowDatabaseP4ssw0rd}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/bank/protocol/openid-connect/certs

spring.security.oauth2.client.registration.bank-api.client-id=${BANK_API_CLIENT_ID}
spring.security.oauth2.client.registration.bank-api.client-secret=${BANK_API_CLIENT_SECRET}
spring.security.oauth2.client.registration.bank-api.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.bank-api.scope=payments.read,payments.write
spring.security.oauth2.client.provider.bank-api.token-uri=http://localhost:8081/realms/bank/protocol/openid-connect/token
