spring.application.name=multidigital-wallet

# Database
spring.datasource.url=jdbc:postgresql://localhost:5432/payflow_db
spring.datasource.username=${POSTGRES_USER:payflowAdmin}
spring.datasource.password=${POSTGRES_PASSWORD:PayflowDatabaseP4ssw0rd}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080

# Keycloak Resource Server config
spring.security.oauth2.resourceserver.jwt.issuer-uri=http://localhost:8081/realms/payflow

# Keycloak Admin Client Config
keycloak.server-url=http://localhost:8081
keycloak.realm=payflow
keycloak.admin.username=${KEYCLOAK_ADMIN_USER:admin}
keycloak.admin.password=${KEYCLOAK_ADMIN_PASSWORD:admin}
keycloak.admin.client-id=admin-cli


spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/realms/payflow/protocol/openid-connect/certs

spring.security.oauth2.client.registration.payflow-api.client-id=${PAYFLOW_API_CLIENT_ID}
spring.security.oauth2.client.registration.payflow-api.client-secret=${PAYFLOW_API_CLIENT_SECRET}
spring.security.oauth2.client.registration.payflow-api.authorization-grant-type=client_credentials
spring.security.oauth2.client.registration.payflow-api.scope=payments.read,payments.write
spring.security.oauth2.client.provider.payflow-api.token-uri=http://localhost:8081/realms/payflow/protocol/openid-connect/token


